server:
  port: 8081 #默認端口
spring:
  profiles:
   active: prod

#默認端口

---
server:
  port: 8083
spring:
  config:
    activate:
      on-profile: dev
---
server:
  port: 8087
spring:
  config:
    activate:
      on-profile: prod
